import type { BlogPost, Portfolio, Service, Page, SupportTicket, MediaFile, DashboardStats } from '../types';
export const mockServices: Service[] = [/* copied data */ 
  { id:'1', title:'Cloud Solutions', slug:'cloud-solutions', description:'Enterprise-grade cloud infrastructure and migration services to scale your business.', icon:'Cloud', features:['AWS, Azure, and GCP integration','Cloud migration and optimization','Serverless architecture','Auto-scaling infrastructure','24/7 monitoring and support'], pricing:{ basic:999, professional:2499, enterprise:5999 }, seo:{ metaTitle:'Cloud Solutions | VertexTech', metaDescription:'Transform your business with our enterprise cloud solutions', keywords:['cloud','infrastructure','AWS','Azure'] } },
  { id:'2', title:'Cybersecurity', slug:'cybersecurity', description:'Comprehensive security solutions to protect your business from modern threats.', icon:'Shield', features:['Threat detection and prevention','Security audits and compliance','Data encryption and protection','Penetration testing','Security training programs'], pricing:{ basic:1499, professional:3499, enterprise:7999 }, seo:{ metaTitle:'Cybersecurity Services | VertexTech', metaDescription:'Protect your business with advanced cybersecurity solutions', keywords:['cybersecurity','security','protection','encryption'] } },
  { id:'3', title:'Custom Software Development', slug:'custom-software', description:'Tailored software solutions built to meet your unique business requirements.', icon:'Code', features:['Full-stack web development','Mobile app development','API design and integration','Legacy system modernization','Ongoing maintenance and support'], pricing:{ basic:4999, professional:9999, enterprise:19999 }, seo:{ metaTitle:'Custom Software Development | VertexTech', metaDescription:'Build custom software solutions for your business', keywords:['software','development','custom','web','mobile'] } },
  { id:'4', title:'Data Analytics', slug:'data-analytics', description:'Turn your data into actionable insights with advanced analytics and BI solutions.', icon:'BarChart3', features:['Business intelligence dashboards','Predictive analytics','Data warehousing','Real-time reporting','AI and machine learning integration'], pricing:{ basic:1999, professional:4999, enterprise:9999 }, seo:{ metaTitle:'Data Analytics Services | VertexTech', metaDescription:'Transform data into insights with our analytics solutions', keywords:['analytics','data','business intelligence','reporting'] } },
];
export const mockBlogPosts: BlogPost[] = [
  { id:'1', title:'The Future of Cloud Computing in 2026', slug:'future-of-cloud-computing-2026', content:'Detailed article content here...', excerpt:'Explore the latest trends and innovations shaping the future of cloud technology.', featuredImage:'https://images.unsplash.com/photo-1667984390553-7f439e6ae401?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080', category:'Cloud Technology', tags:['Cloud','Innovation','Technology'], author:{ id:'1', name:'Sarah Johnson', avatar:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop' }, seo:{ metaTitle:'The Future of Cloud Computing in 2026', metaDescription:'Explore cloud computing trends and innovations', keywords:['cloud','computing','future','trends'] }, publishedAt:'2026-02-15T10:00:00Z', status:'published' },
  { id:'2', title:'Cybersecurity Best Practices for Enterprises', slug:'cybersecurity-best-practices', content:'Detailed article content here...', excerpt:'Essential security practices every enterprise should implement to protect their data.', featuredImage:'https://images.unsplash.com/photo-1768224656445-33d078c250b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080', category:'Security', tags:['Cybersecurity','Best Practices','Enterprise'], author:{ id:'2', name:'Michael Chen', avatar:'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop' }, seo:{ metaTitle:'Cybersecurity Best Practices for Enterprises', metaDescription:'Learn essential cybersecurity practices for your business', keywords:['cybersecurity','security','best practices','enterprise'] }, publishedAt:'2026-02-20T14:30:00Z', status:'published' },
  { id:'3', title:'Building Scalable Applications with Microservices', slug:'microservices-architecture', content:'Detailed article content here...', excerpt:'Learn how microservices architecture can help you build more scalable and maintainable applications.', featuredImage:'https://images.unsplash.com/photo-1617042375876-a13e36732a04?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080', category:'Development', tags:['Microservices','Architecture','Development'], author:{ id:'1', name:'Sarah Johnson', avatar:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop' }, seo:{ metaTitle:'Building Scalable Applications with Microservices', metaDescription:'Guide to microservices architecture', keywords:['microservices','architecture','scalable','applications'] }, publishedAt:'2026-02-25T09:00:00Z', status:'published' },
];
export const mockPortfolio: Portfolio[] = [
  { id:'1', title:'Global Bank Digital Transformation', slug:'global-bank-digital-transformation', client:'Global Financial Corp', description:'Complete digital transformation of banking infrastructure with cloud migration and modern web applications.', technologies:['React','Node.js','AWS','MongoDB','Kubernetes'], gallery:['https://images.unsplash.com/photo-1551288049-bebda4e38f71?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080','https://images.unsplash.com/photo-1633250391894-397930e3f5f2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080'], testimonial:{ quote:'VertexTech transformed our entire digital infrastructure. Their expertise was invaluable.', author:'John Smith', position:'CTO, Global Financial Corp' }, featured:true, completedAt:'2025-12-15' },
  { id:'2', title:'HealthTech Patient Management System', slug:'healthtech-patient-system', client:'MediCare Solutions', description:'HIPAA-compliant patient management system with real-time data synchronization and telemedicine features.', technologies:['Vue.js','Python','PostgreSQL','Redis','WebRTC'], gallery:['https://images.unsplash.com/photo-1646153114001-495dfb56506d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080'], testimonial:{ quote:'The system has revolutionized how we manage patient care. Outstanding work!', author:'Dr. Emily Roberts', position:'Medical Director, MediCare Solutions' }, featured:true, completedAt:'2026-01-20' },
  { id:'3', title:'E-Commerce Platform Redesign', slug:'ecommerce-platform-redesign', client:'RetailPro Inc', description:'Complete redesign and optimization of e-commerce platform with AI-powered recommendations.', technologies:['Next.js','GraphQL','Stripe','TensorFlow','GCP'], gallery:['https://images.unsplash.com/photo-1633250391894-397930e3f5f2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080'], featured:false, completedAt:'2025-11-30' },
];
export const mockTickets: SupportTicket[] = [
  { id:'1', userId:'3', subject:'Website performance issue', description:'The website is loading slowly on mobile devices.', status:'in-progress', priority:'high', responses:[{ id:'1', userId:'1', userName:'Admin User', message:'We are looking into this issue. Can you provide more details about which pages are affected?', createdAt:'2026-03-02T10:00:00Z' }], createdAt:'2026-03-01T14:30:00Z', updatedAt:'2026-03-02T10:00:00Z' },
  { id:'2', userId:'3', subject:'Feature request: Dark mode', description:'Would love to see a dark mode option for the dashboard.', status:'open', priority:'medium', responses:[], createdAt:'2026-02-28T09:15:00Z', updatedAt:'2026-02-28T09:15:00Z' },
];
export const mockDashboardStats: DashboardStats = { users:1234, pages:45, posts:128, projects:67, tickets:23 };
export const mockMediaFiles: MediaFile[] = [
  { id:'1', name:'hero-banner.jpg', url:'https://images.unsplash.com/photo-1646153114001-495dfb56506d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080', type:'image', size:2456789, uploadedAt:'2026-02-15T10:00:00Z', uploadedBy:'Admin User' },
  { id:'2', name:'team-photo.jpg', url:'https://images.unsplash.com/photo-1758518731468-98e90ffd7430?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080', type:'image', size:1876543, uploadedAt:'2026-02-20T14:30:00Z', uploadedBy:'Editor User' },
];
